# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod


      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm install -D --save autoprefixer
      - run: npm install -D --save postcss-cli
#      - run: git submodule update --init --recursive

      - name: Build hugo
        run: hugo --gc --minify

#      - name: Git init
#        run: |
#          git config --global user.name '${{github.actor}}'
#          git config --global user.email '${{github.actor}}@users.noreply.github.com'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
